### ISSUE TITLE
init-container fails with nfs-subdir-external-provisioner

### ISSUE THREAD

**Issue by nuggie** [TriliumNext/helm-charts#4]
Hi dev,

when using the helm chart with nfs-subdir-external-provisioner the init-container "fixperm" fails with the following message:

chown: /home/node/trilium-data: Operation not permitted

This happens on a newly created PVC with nfs-client and RWO permissions.

**Comment by Wtfitsaduck** [comment]
Good shout! Fixing in #5

**Comment by perfectra1n** [comment]
@nuggie please feel free to try v1.1.1 of the chart, and let me know if you still have any issues.
